AmeWebApps/Controllers/BuildSheetsController.cs
using AmeWebApps.Models;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing.Printing;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Mail;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Word = Microsoft.Office.Interop.Word;
//using Microsoft.Office.Tools.Word;

namespace AmeWebApps.Controllers
{
    public class BuildSheetsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TestPrint(string SendName="shawn_connolly", string SendDomain="amemusic", string ToAddr="shawn_connolly@amemusic.com")
        {
                MailMessage mail = new MailMessage();
                SmtpClient smtpServer = new SmtpClient("exchange.local.rpm.com");
                smtpServer.Credentials = new System.Net.NetworkCredential("SConnolly", "s1987Conno!!y");
                smtpServer.Port = 25;
                string SendAddr = SendName + "@" + SendDomain + ".com";
                mail.From = new MailAddress(SendAddr);
                mail.To.Add(ToAddr);
                mail.Subject = "Hey our test is starting up again!";
                mail.IsBodyHtml = true;
                mail.Body = "<html><head></head><body></body></html>";    

                smtpServer.Send(mail);

            return View();
        }

        public ActionResult DeleteEntry(int systemID)
        {
            if (systemID != null || systemID != 0)
            {
                string connString = "server=WEB-APPS-1; database=AmeMaster; uid=sa; password=topdog; MultipleActiveResultSets=true";
                using (var conn = new SqlConnection(connString))
                {
                    var deleteQry = String.Format("delete from AME_BUILD_SHEET where system_id = {0}", systemID);
                    using (var cmd = new SqlCommand(deleteQry, conn))
                    {
                        conn.Open();
                        cmd.ExecuteNonQuery();
                        conn.Close();
                    }
                }
            }

            return View();
        }

        public ActionResult ViewShipped()
        {
            List<AME_BUILD_SHEET> bsList = new List<AME_BUILD_SHEET>();
            bsList = new AmeMasterEntities().AME_BUILD_SHEET.Where(x => x.TRACKING_NUM != null).ToList();

            foreach (var bs in bsList)
            {
                if (!String.IsNullOrEmpty(bs.DATE_SHIPPED))
                {
                    bs.DATE_SHIPPED = Convert.ToDateTime(bs.DATE_SHIPPED).ToString("yyyy/MM/dd");
                }
            }

            bsList = bsList.OrderByDescending(x => x.DATE_SHIPPED).ToList();

            return View(bsList);
        }

        public ActionResult PrintList()
        {
            List<BuildSheetListModel> bsList = new List<BuildSheetListModel>();
            bsList = BuildSheetListDA.GetBuildSheetList().Where(x => x.ALREADY_PRINTED == false).ToList();

            return View(bsList);
        }

        public ActionResult VerifyBuildSheet(int systemID)
        {
            BuildSheetModel bsModel = new BuildSheetModel();
            bsModel = BuildSheetModelDA.GetModel(systemID);
            if (!String.IsNullOrEmpty(bsModel.ADDITIONAL_INSTRUCTIONS))
            {
                bsModel.ADDITIONAL_INSTRUCTIONS = bsModel.ADDITIONAL_INSTRUCTIONS.Replace("'", "`");
                bsModel.ADDITIONAL_INSTRUCTIONS = bsModel.ADDITIONAL_INSTRUCTIONS.Replace("<", "");
            }
            if (!String.IsNullOrEmpty(bsModel.PROFILE_NAME))
            {
                bsModel.PROFILE_NAME = bsModel.PROFILE_NAME.Replace("'", "`");
                bsModel.PROFILE_NAME = bsModel.PROFILE_NAME.Replace("<", "");
            }
            if (!String.IsNullOrEmpty(bsModel.BRANCH_NAME))
            {
                bsModel.BRANCH_NAME = bsModel.BRANCH_NAME.Replace("'", "`");
                bsModel.BRANCH_NAME = bsModel.BRANCH_NAME.Replace("<", "");
            }
            if (!String.IsNullOrEmpty(bsModel.COMPANY_NAME))
            {
                bsModel.COMPANY_NAME = bsModel.COMPANY_NAME.Replace("'", "`");
                bsModel.COMPANY_NAME = bsModel.COMPANY_NAME.Replace("<", "");
            }
            if (!(String.IsNullOrEmpty(bsModel.REPLACING_NAME)))
            {
                bsModel.REPLACING_TYPE = Convert.ToInt32(bsModel.REPLACING_NAME.Substring(4, 1));
            }
            else
            {
                bsModel.REPLACING_TYPE = 8;
            }

            return View(bsModel);
        }

        public ActionResult EditList()
        {
            List<BuildSheetListModel> bsList = new List<BuildSheetListModel>();
            bsList = BuildSheetListDA.GetBuildSheetList().Where(x => x.ALREADY_PRINTED == true).ToList();

            return View(bsList);
        }

        public ActionResult EditBuildSheet(int systemID)
        {
            AmeMasterEntities AME = new AmeMasterEntities();
            AME_BUILD_SHEET bsModel = new AME_BUILD_SHEET();
            bsModel = AME.AME_BUILD_SHEET.Where(x => x.SYSTEM_ID == systemID).First();

            return View(bsModel);
        }

        public ActionResult AddShippingInfoList(int? showHidden)
        {
            List<AME_BUILD_SHEET> bsList = new List<AME_BUILD_SHEET>();
            AmeMasterEntities AME = new AmeMasterEntities();
            bsList = AME.AME_BUILD_SHEET.Where(x => String.IsNullOrEmpty(x.TRACKING_NUM)).OrderBy(x => x.SHIP_BY_DATE).ToList();
            if (showHidden == 1)
            {
                bsList = bsList.Concat(AME.AME_BUILD_SHEET.Where(x => x.TRACKING_NUM == "HIDDEN")).ToList();
                bsList.OrderBy(x => x.SHIP_BY_DATE);
            }
            return View(bsList);

        }

        public ActionResult HideBuildsheet(int systemID)
        {
            string connString = "server=WEB-APPS-1; database=AmeMaster; uid=sa; password=topdog; MultipleActiveResultSets=true";
            using (var conn = new SqlConnection(connString))
            {
                var updateQry = String.Format("UPDATE AME_BUILD_SHEET set TRACKING_NUM = 'HIDDEN' WHERE SYSTEM_ID = {0}", systemID);
                using (var cmd = new SqlCommand(updateQry, conn))
                {
                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();
                }
            }
            List<AME_BUILD_SHEET> bsList = new List<AME_BUILD_SHEET>();
            AmeMasterEntities AME = new AmeMasterEntities();
            bsList = AME.AME_BUILD_SHEET.Where(x => String.IsNullOrEmpty(x.TRACKING_NUM)).OrderBy(x => x.SHIP_BY_DATE).ToList();

            return View("AddShippingInfoList", bsList);
        }

        public ActionResult PrintFinalBuildSheet(int systemID, string TRACKING_NUM, string RETURN_NUM, string SHIP_MTHD)
        {
            RPMModels RPM = new RPMModels();
            RPM_CLIENT_SYSTEM systemModel = new RPM_CLIENT_SYSTEM();
            systemModel = RPM.RPM_CLIENT_SYSTEM.Where(x => x.SYSTEM_ID == systemID).First();

            var DATE_BUILT = systemModel.DATE_BUILT.ToString();
            var DATE_SHIPPED = DateTime.Now.ToString();
            var TAG_NUMBER = systemModel.COMPUTER_NAME;

            string connString = "server=WEB-APPS-1; database=AmeMaster; uid=sa; password=topdog; MultipleActiveResultSets=true";
            using (var conn = new SqlConnection(connString))
            {
                var updateQry = String.Format("UPDATE AME_BUILD_SHEET set DATE_BUILT = '{0}', DATE_SHIPPED = '{1}', TAG_NUMBER = '{2}', TRACKING_NUM = '{3}', RETURN_SLIP_TRACKING_NUM = '{4}', SHIPPING_METHOD = '{5}' where SYSTEM_ID = {6}", DATE_BUILT, DATE_SHIPPED, TAG_NUMBER, TRACKING_NUM, RETURN_NUM, SHIP_MTHD, systemID);
                using (var cmd = new SqlCommand(updateQry, conn))
                {
                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();
                }
            }

            string connString2 = "server=AME-DATA-02; database=AmeMaster; uid=sa; password=topdog; MultipleActiveResultSets=true";
            using (var conn = new SqlConnection(connString2))
            {
                var updateQry = String.Format("UPDATE RPM_CLIENT_SYSTEM set SYSTEM_STATUS = 'SHIPPED', DATE_SHIPPED = getdate() where system_id = {0} and SYSTEM_STATUS='BUILT'", systemID);
                using (var cmd = new SqlCommand(updateQry, conn))
                {
                    conn.Open();
                    cmd.ExecuteNonQuery();
                    conn.Close();
                }
            }

            string filePath = null;
            string newFilePath = @"\\AME-FILE-01\Apps\Buildsheets\" + systemID + "f.docx";
            if (System.IO.File.Exists(@"\\AME-FILE-01\Apps\Buildsheets\" + systemID + "e.docx"))
            {
                filePath = @"\\AME-FILE-01\Apps\Buildsheets\" + systemID + "e.docx";
            }
            else
            {
                filePath = @"\\AME-FILE-01\Apps\Buildsheets\" + systemID + ".docx";
            }

            System.IO.File.Copy(filePath, newFilePath, true);

            

            using (WordprocessingDocument doc = WordprocessingDocument.Open(newFilePath, true))
            {
                string docText = null;
                using (StreamReader sr = new StreamReader(doc.MainDocumentPart.GetStream()))
                {
                    docText = sr.ReadToEnd();
                }

                Regex rxText = new Regex("");

                if (!String.IsNullOrEmpty(DATE_BUILT))
                {
                    rxText = new Regex("DATE_BUILT");
                    docText = rxText.Replace(docText, DATE_BUILT);

AmeWebApps/Views/BuildSheets/AddShippingInfoList.cshtml
@model List<AmeWebApps.Models.AME_BUILD_SHEET>

@{
    ViewBag.Title = "Add Shipping Information";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 50);
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}
<p style="text-align: center;">
    @Html.ActionLink("Show Hidden", "AddShippingInfoList", new { showHidden = 1 })
    @Html.ActionLink("Unshow Hidden", "AddShippingInfoList")
</p>

@grid.GetHtml(
tableStyle: "webGrid",
headerStyle: "header",
alternatingRowStyle: "alt",
columns: grid.Columns(
grid.Column(columnName: "SHIP_BY_DATE", header: "Ship By", format: item => item.SHIP_BY_DATE == "0" ? "ASAP" : item.SHIP_BY_DATE),
    grid.Column(columnName: "SYSTEM_ID", header: "System ID"),
    grid.Column(columnName: "COMPANY_NAME", header: "Company"),
    grid.Column(columnName: "BRANCH_NAME", header: "Branch"),
    grid.Column(columnName: "PRINT", header: "Complete Buildsheet", format: item => Html.ActionLink((string)"Add Shipping Info", (string)"AddShippingInfo", new { systemID = (int)item.SYSTEM_ID })),
    grid.Column(columnName: "Hide", header: "Hide", format: item => Html.ActionLink((string)"Hide", (string)"HideBuildsheet", new { systemID = (int)item.SYSTEM_ID }))
))

AmeWebApps/Views/BuildSheets/DeleteEntry.cshtml
@{
    ViewBag.Title = "Entry Removed";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@Html.ActionLink("Back to list", "AddShippingInfoList") <br />
@Html.ActionLink("Back to index", "Index")

AmeWebApps/Views/BuildSheets/EditBuildSheet.cshtml
@model AmeWebApps.Models.AME_BUILD_SHEET
@{
    ViewBag.Title = "Edit Build Sheet Info";
    if (Model.INSTALL_DATE == "ASAP")
    {
        Model.INSTALL_DATE = DateTime.Now.ToString();
    }
    if (Model.SHIP_BY_DATE == "0")
    {
        Model.SHIP_BY_DATE = DateTime.Now.ToString();   
    }
    if (Model.ARRIVE_BY_DATE == "ASAP")
    {
        Model.ARRIVE_BY_DATE = DateTime.Now.ToString();   
    }
    if (Model.SHIP_TO_TYPE == "Shipping Address")
    {
        Model.SHIP_TO_TYPE = "SHIPPING";   
    }
    if (Model.SHIP_TO_TYPE == "Installed at Address")
    {
        Model.SHIP_TO_TYPE = "INSTALLED";   
    }
    if (Model.SHIP_TO_TYPE == "Custom Address")
    {
        Model.SHIP_TO_TYPE = "CUSTOM";   
    }
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}
<script type="text/javascript">
    $(function () {
        $("#custom-shipping").hide();
        $("#INSTALL_DATE").val(new Date('@Model.INSTALL_DATE').toJSON().slice(0, 10));
        $("#SHIP_BY_DATE").val(new Date('@Model.SHIP_BY_DATE').toJSON().slice(0, 10));
        @if(!String.IsNullOrEmpty(Model.ARRIVE_BY_DATE)){
            <text>$("#ARRIVE_BY_DATE").val(new Date('@Model.ARRIVE_BY_DATE').toJSON().slice(0, 10));</text>
        } else {
        <text>
        var now = new Date();
        var month = (now.getMonth() + 1);
        var day = now.getDate();
        if (month < 10)
            month = "0" + month;
        if (day < 10)
            day = "0" + day;
        var today = now.getFullYear() + '-' + month + '-' + day;
        $("#ARRIVE_BY_DATE").val(today);
        </text>   
        }
        $('select[name="REPLACING_TYPE"]').find('option[value="@Model.REPLACING_TYPE"]').attr("selected", true);
        
        $("#COMM_@Model.COMM_TYPE").attr('checked', 'checked');
        $("#PACK_@Model.PACKAGING_TYPE").attr('checked', 'checked');
        $("#SHIP_@Model.SHIP_TO_TYPE").attr('checked', 'checked');
    });
    function shipto(addr) {
        if (addr == "custom") {
            $("#custom-shipping").show();
        }
        else {
            $("#custom-shipping").hide();
        }
    };
</script>
<style>
    input {
        width: 225px;
    }
    th {
        padding: 10px;
    }
    td {
        padding-left: 15px;
        padding-right: -15px;
    }
    table {
        background-color: #FFFFFF;
        box-shadow: 2px 2px 5px lightgrey;
    }
</style>

<h2>Build Sheet</h2>

@using (Html.BeginForm("UpdateBuildSheet", "BuildSheets")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BuildsheetModel</legend>
        <input type="hidden" name="REPLACING_NAME" id="REPLACING_NAME" value="@Model.REPLACING_NAME"/>
        <input type="hidden" name="BUILD_SHEET_ID" id="BUILD_SHEET_ID" value="@Model.BUILD_SHEET_ID" />
        <table style="width:850px;">
            <tr>
                <th colspan="4"><b><u>Request Information</u></b></th>
            </tr>
            <tr>
                <td>Install Date</td>
                <td>
                    <input type="date" id="INSTALL_DATE" name="INSTALL_DATE"/>
                </td>
                <td>Ship By</td>
                <td>
                    <input type="date" id="SHIP_BY_DATE" name="SHIP_BY_DATE"/>
                </td>
            </tr>
            <tr>
                <td>Profile Size</td>
                <td>
                    @Html.EditorFor(model => model.PROFILE_SIZE)
                    @Html.ValidationMessageFor(model => model.PROFILE_SIZE)
                </td>
                <td>Client ID</td>
                <td>
                    @Html.EditorFor(model => model.CLIENT_ID)
                    @Html.ValidationMessageFor(model => model.CLIENT_ID)
                </td>
            </tr>
            <tr>
                <td># of Zones</td>
                <td>
                    @Html.EditorFor(model => model.NUM_ZONES)
                    @Html.ValidationMessageFor(model => model.NUM_ZONES)
                </td>
                <td>Client Name</td>
                <td>
                    @Html.EditorFor(model => model.COMPANY_NAME)
                    @Html.ValidationMessageFor(model => model.COMPANY_NAME)
                </td>
            </tr>
            <tr>
                <td>System ID</td>
                <td>
                    @Html.EditorFor(model => model.SYSTEM_ID)
                    @Html.ValidationMessageFor(model => model.SYSTEM_ID)
                </td>
                <td>Branch</td>
                <td>
                    @Html.EditorFor(model => model.BRANCH_NAME)
                    @Html.ValidationMessageFor(model => model.BRANCH_NAME)
                </td>
            </tr>
            <tr style="height:48px;">
                <td>Use Refurb?</td>
                <td>
                    @Html.EditorFor(model => model.USE_REFURB)
                    @Html.ValidationMessageFor(model => model.USE_REFURB)
                </td>
                <td>Replacing Type</td>
                <td>
                    <select name="REPLACING_TYPE">
                        <option value="" id="rptype_8">New Receiver</option>
                        <option value="1" id="rptype_1">Model 1</option>
                        <option value="2" id="rptype_2">Model 2</option>
                        <option value="3" id="rptype_3">Model 3</option>
                        <option value="4" id="rptype_4">Model 4</option>
                        <option value="5" id="rptype_5">Model 5</option>
                        <option value="7" id="rptype_6">Model 7</option>
                        <option value="6" id="rptype_7">Video Receiver</option>
                    </select>
                </td>
            </tr>
            <tr style="height:48px;">
                <td>Comm Type</td>
                <td>
                    <span style="padding-right:20px;">WAN <input type="radio" value="WAN" id="COMM_WAN" name="COMM_TYPE" style="padding-left: 5px; width: 20px;" /></span>
                    <span style="padding-right:20px;">Dial-up <input type="radio" value="Dial-Up" id="COMM_DIALUP" name="COMM_TYPE" style="padding-left: 5px; width: 20px;" /></span>
                </td>
            </tr>
            <tr><td></td></tr>
        </table>            
        <table style="width:850px;">
            <tr>
                <th><b><u>Shipping Information</u></b></th>
            </tr>
            <tr>
                <td>Arrive By</td>
                <td>
                    <input type="date" name="ARRIVE_BY_DATE" id="ARRIVE_BY_DATE" />
                    @Html.ValidationMessageFor(model => model.ARRIVE_BY_DATE)
                </td>
            </tr>
            <tr style="height:48px;">
                <td>Packaging</td>
                <td>
                    <span>New <input type="radio" name="PACK_TYPE" id="PACK_New" value="New" style="padding-left:5px; width:20px;" /></span>
                    <span style="padding-left: 20px;">Replacement <input type="radio" name="PACK_TYPE" id="PACK_Replacement" value="Replacement" style="padding-left:5px; width:20px;" /></span>
                </td>
            </tr>
            <tr style="height:48px;">
                <td>Include Return Label</td>
                <td>
                    @Html.EditorFor(model => model.RETURN_LABEL)
                    @Html.ValidationMessageFor(model => model.RETURN_LABEL)
                </td>
            </tr>
            <tr style="height:48px;">
                <td>Ship To</td>
                <td>
                    <span>Installed at Address <input type="radio" value="Installed at Address" id="SHIP_INSTALLED" name="SHIP_TO" style="padding-left:5px; width:20px;" onclick="shipto('installed')"/></span>
                    <span style="padding-left:20px;">Shipping Address <input type="radio" value="Shipping Address" id="SHIP_SHIPPING" name="SHIP_TO" style="padding-left:5px; width:20px;" onclick="shipto('shipping')"/></span>
                    <span style="padding-left:20px;">Custom Address <input type="radio" value="Custom Address" name="SHIP_TO" id="SHIP_CUSTOM" style="padding-left:5px; width:20px;" onclick="shipto('custom')"/></span>
                </td>
            </tr>
        </table>

        <div id="custom-shipping">
            <table style="width:850px;">
                <tr>
                    <th colspan="6"><b><u>Custom Shipping Information</u></b></th>
                </tr>
                <tr>
                    <td>Attention</td>
                    <td colspan="5">
                        @Html.EditorFor(model => model.CUSTOM_ADDR_ATTN)
                        @Html.ValidationMessageFor(model => model.CUSTOM_ADDR_ATTN)
                    </td>
                </tr>
                <tr>
                    <td>Street</td>
                    <td colspan="5">
                        @Html.EditorFor(model => model.CUSTOM_ADDR_1)
                        @Html.ValidationMessageFor(model => model.CUSTOM_ADDR_1)
                    </td>
                </tr>
                <tr>
                    <td>Apartment/Suite/Unit</td>
                    <td colspan="5">
                        @Html.EditorFor(model => model.CUSTOM_ADDR_2)
                        @Html.ValidationMessageFor(model => model.CUSTOM_ADDR_2)
                    </td>
                </tr>
                <tr>
                    <td>City</td>
                    <td>
                        <input type="text" id="CUSTOM_ADDR_CITY" name="CUSTOM_ADDR_CITY" value="@Model.CUSTOM_ADDR_CITY" style="width:100px;" />
                        @Html.ValidationMessageFor(model => model.CUSTOM_ADDR_CITY)
                    </td>
                    <td>State</td>
                    <td>
                        <input type="text" id="CUSTOM_ADDR_STATE" name="CUSTOM_ADDR_STATE" value="@Model.CUSTOM_ADDR_STATE" style="width:100px;" />
                        @Html.ValidationMessageFor(model => model.CUSTOM_ADDR_STATE)
                    </td>
                    <td>Zip Code</td>
                    <td>
                        <input type="text" id ="CUSTOM_ADDR_ZIP" name="CUSTOM_ADDR_ZIP" value="@Model.CUSTOM_ADDR_ZIP" style="width:100px;"/>
                        @Html.ValidationMessageFor(model => model.CUSTOM_ADDR_ZIP)
                    </td>
                </tr>
            </table>
        </div>

        <table style="width:850px;">
            <tr>
                <th><b><u>Additional Instructions</u></b></th>
            </tr>
            <tr>
                <td>
                    <input type="text" name="ADDITIONAL_INSTRUCTIONS" id="ADDITIONAL_INSTRUCTIONS" value="@Model.ADDITIONAL_INSTRUCTIONS" style="width:600px;"/>
                    @Html.ValidationMessageFor(model => model.ADDITIONAL_INSTRUCTIONS)
                </td>
            </tr>
        </table>

        <p>
            <input type="submit" value="Update and Print!" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to list", "PrintList", "BuildSheets")
</div>

AmeWebApps/Views/BuildSheets/EditList.cshtml
@model List<AmeWebApps.Models.BuildSheetListModel>
@{
    ViewBag.Title = "Edit Build Sheets";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 50);
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@grid.GetHtml(
tableStyle: "webGrid",
headerStyle: "header",
alternatingRowStyle: "alt",
columns: grid.Columns(
    grid.Column(columnName: "SYSTEM_ID", header: "System ID"),
    grid.Column(columnName:"COMPANY_NAME", header: "Company"),
    grid.Column(columnName:"BRANCH", header: "Branch"),
    grid.Column(columnName:"PRINT", header: "Edit Buildsheet", format: item => Html.ActionLink((string)"Edit & Reprint", (string)"EditBuildSheet", new { systemID = (int)item.SYSTEM_ID})) 
))

AmeWebApps/Views/BuildSheets/Index.cshtml
@{
    ViewBag.Title = "Build Sheets Index";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

<ul style="list-style:none;">
    <li>@Html.ActionLink("Print Build Sheet", "PrintList")</li>
    <li>@Html.ActionLink("Edit and Reprint Build Sheet", "EditList")</li>
    <li>@Html.ActionLink("Add Shipping Information", "AddShippingInfoList")</li>
    <li>@Html.ActionLink("View Shipped Receivers", "ViewShipped")</li>
</ul>

AmeWebApps/Views/BuildSheets/Print.cshtml
@{
    ViewBag.Title = "Print Build Sheet";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Success!</h1>
            </hgroup>
        </div>
    </section>
}

<ul>
    <li>Back to print list</li>
    <li>Back to index</li>
</ul>

AmeWebApps/Views/BuildSheets/PrintBatchBuildsheets.cshtml
@{
    ViewBag.Title = "Print Batch Buildsheets";
}

<p>Done.</p>

AmeWebApps/Views/BuildSheets/PrintBuildSheet.cshtml
@{
    ViewBag.Title = "Build Sheet Printed!";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@Html.ActionLink("Back to list", "PrintList") <br />
@Html.ActionLink("Back to index", "Index")

AmeWebApps/Views/BuildSheets/PrintFinalBuildSheet.cshtml
@{
    ViewBag.Title = "Build Sheet Complete!";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@Html.ActionLink("Back to list", "AddShippingInfoList") <br />
@Html.ActionLink("Back to index", "Index")

AmeWebApps/Views/BuildSheets/PrintFinalBuildSheetBatch.cshtml
@{
    ViewBag.Title = "PrintFinalBuildSheetBatch";
}

<h2>Done</h2>

AmeWebApps/Views/BuildSheets/PrintList.cshtml
@model List<AmeWebApps.Models.BuildSheetListModel>
@{
    ViewBag.Title = "Print Build Sheets";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 50);
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@grid.GetHtml(
tableStyle: "webGrid",
headerStyle: "header",
alternatingRowStyle: "alt",
columns: grid.Columns(
    grid.Column(columnName: "SYSTEM_ID", header: "System ID"),
    grid.Column(columnName:"COMPANY_NAME", header: "Company"),
    grid.Column(columnName:"BRANCH", header: "Branch"),
    grid.Column(columnName:"PRINT", header: "Print Buildsheet", format: item => Html.ActionLink((string)"Verify & Print", (string)"VerifyBuildSheet", new { systemID = (int)item.SYSTEM_ID})) 
))

AmeWebApps/Views/BuildSheets/TestPrint.cshtml
@{
    ViewBag.Title = "TestPrint";
}

<h2>Test Print</h2>

AmeWebApps/Views/BuildSheets/UpdateBuildSheet.cshtml
@{
    ViewBag.Title = "Build Sheet Updated!";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@Html.ActionLink("Back to list", "EditList") <br />
@Html.ActionLink("Back to index", "Index")