AmeWebApps/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AmeWebApps.Models;
using System.Data.SqlClient;
using AmeWebApps.Models.TicketNotesDSTableAdapters;
using AmeWebApps.Models.TicketStepsDSTableAdapters;

namespace AmeWebApps.Controllers
{
    public class TicketsController : Controller
    {
        private AmeTicketsEntities1 db = new AmeTicketsEntities1();

        //
        // GET: /Tickets/

        public ActionResult Index()
        {
            return View(db.AME_TICKET.OrderByDescending(x=> x.DATE_OPENED).ToList());
        }

        public ActionResult FindReceiver()
        {
            return View();
        }


        //
        // GET: /Tickets/Details/5

        public ActionResult Details(int id = 0)
        {
            AME_TICKET ame_ticket = db.AME_TICKET.Find(id);
            if (ame_ticket == null)
            {
                return HttpNotFound();
            }
            return View(ame_ticket);
        }

        //
        // GET: /Tickets/Create

        public ActionResult Create(string COMPUTER_NAME)
        {
            if (!String.IsNullOrEmpty(COMPUTER_NAME))
            {
                string connString = "server=192.168.0.24; database=AmeMaster; uid=sa; password=topdog;";
                try
                {
                    using (SqlConnection conn = new SqlConnection(connString))
                    {
                        if (COMPUTER_NAME.Length > 6)
                        {
                            COMPUTER_NAME = COMPUTER_NAME.Substring(4, 6);
                        }
                        string sqlQry = String.Format("select rcs.CLIENT_ID, rca.COMPANY_NAME, rca.BRANCH, rcs.COMPUTER_NAME, rcl.NOTES from RPM_CLIENT_SYSTEM rcs inner join RPM_CLIENT_LOCATION rcl on rcs.LOCATION_ID = rcl.LOCATION_ID inner join RPM_CLIENT_ADDRESS rca on rcl.ADDRESS_ID = rca.ADDRESS_ID where rcs.COMPUTER_NAME like 'AME_{0}'", COMPUTER_NAME);
                        using (SqlCommand cmd = new SqlCommand(sqlQry, conn))
                        {
                            conn.Open();
                            SqlDataReader reader = cmd.ExecuteReader();
                            if (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    ViewData["COMPUTER_NAME"] = reader.GetString(reader.GetOrdinal("COMPUTER_NAME"));
                                    ViewData["CLIENT_ID"] = reader.GetInt32(reader.GetOrdinal("CLIENT_ID")).ToString();
                                    ViewData["COMPANY_NAME"] = reader.GetString(reader.GetOrdinal("COMPANY_NAME"));
                                    ViewData["BRANCH"] = reader.GetString(reader.GetOrdinal("BRANCH"));
                                    var notes = reader.GetString(reader.GetOrdinal("NOTES"));
                                    notes = notes.Replace(System.Environment.NewLine, @"<br/>");
                                    ViewData["NOTES"] = notes.ToString();
                                }
                            }
                            conn.Close();
                        }
                    }
                }
                catch (Exception e32)
                {
                    Console.Write(e32.ToString());
                }
            }
            return View();
        }

        //
        // POST: /Tickets/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AME_TICKET ame_ticket)
        {
            if (ModelState.IsValid)
            {
                db.AME_TICKET.Add(ame_ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ame_ticket);
        }

        //
        // GET: /Tickets/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AME_TICKET ame_ticket = db.AME_TICKET.Find(id);

            TicketNotesDS.AME_TICKET_NOTEDataTable TicketNoteDS = new TicketNotesDS.AME_TICKET_NOTEDataTable();
            AME_TICKET_NOTETableAdapter TicketNoteTA = new AME_TICKET_NOTETableAdapter();
            TicketNoteTA.Fill(TicketNoteDS);

            TicketStepsDS.AME_TICKET_STEPSDataTable TicketStepsDS = new TicketStepsDS.AME_TICKET_STEPSDataTable();
            AME_TICKET_STEPSTableAdapter TicketStepsTA = new AME_TICKET_STEPSTableAdapter();
            TicketStepsTA.Fill(TicketStepsDS);

            if (ame_ticket == null)
            {
                return HttpNotFound();
            }

            ViewBag.tNotes = TicketNoteDS.Where(x => x.TICKET_NOTE_ID == ame_ticket.TICKET_ID).OrderByDescending(x=>x.DATE_MODIFIED);
            ViewBag.tSteps = TicketStepsDS.Where(x => x.TICKET_ID == ame_ticket.TICKET_ID).FirstOrDefault();

            return View(ame_ticket);
        }

        //
        // POST: /Tickets/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AME_TICKET ame_ticket, string oNotes, bool cb_exp = false, bool cb_pwr = false, bool cb_cdtray = false, bool cb_cables = false, bool cb_amp = false)
        {
            TicketNotesDS.AME_TICKET_NOTEDataTable TicketNoteDS = new TicketNotesDS.AME_TICKET_NOTEDataTable();
            AME_TICKET_NOTETableAdapter TicketNoteTA = new AME_TICKET_NOTETableAdapter();
            TicketNoteTA.Fill(TicketNoteDS);

            TicketStepsDS.AME_TICKET_STEPSDataTable TicketStepsDS = new TicketStepsDS.AME_TICKET_STEPSDataTable();
            AME_TICKET_STEPSTableAdapter TicketStepsTA = new AME_TICKET_STEPSTableAdapter();
            TicketStepsTA.Fill(TicketStepsDS);
            var tSteps = TicketStepsDS.Where(x => x.TICKET_ID == ame_ticket.TICKET_ID).FirstOrDefault();

            if (ModelState.IsValid)
            {
                if (tSteps == null)
                {
                    var newTSteps = TicketStepsDS.NewAME_TICKET_STEPSRow();
                    newTSteps.TICKET_ID = ame_ticket.TICKET_ID;
                    newTSteps.chk_expiration = cb_exp;
                    newTSteps.chk_power = cb_pwr;
                    newTSteps.chk_cd_tray = cb_cdtray;
                    newTSteps.chk_cables = cb_cables;
                    newTSteps.chk_amp = cb_amp;
                    TicketStepsDS.AddAME_TICKET_STEPSRow(newTSteps);
                }
                else
                {
                    tSteps.chk_amp = cb_amp;
                    tSteps.chk_cables = cb_cables;
                    tSteps.chk_cd_tray = cb_cdtray;
                    tSteps.chk_expiration = cb_exp;
                    tSteps.chk_power = cb_pwr;
                    TicketStepsTA.Update(tSteps);
                }
            }
            TicketStepsTA.Update(TicketStepsDS);


            if (!(String.IsNullOrEmpty(oNotes)))
            {
                var newTNote = TicketNoteDS.NewAME_TICKET_NOTERow();
                newTNote.TICKET_NOTE_ID = ame_ticket.TICKET_ID;
                newTNote.TICKET_NOTE = oNotes;
                newTNote.DATE_MODIFIED = DateTime.Now;
                newTNote.ADDED_BY = User.Identity.Name.Substring(4);
                TicketNoteDS.AddAME_TICKET_NOTERow(newTNote);
            }

            TicketNoteTA.Update(TicketNoteDS);

            if (ModelState.IsValid)
            {
                db.Entry(ame_ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            

            return View(ame_ticket);
        }

        //
        // GET: /Tickets/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AME_TICKET ame_ticket = db.AME_TICKET.Find(id);
            if (ame_ticket == null)
            {
                return HttpNotFound();
            }
            return View(ame_ticket);
        }

        //
        // POST: /Tickets/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AME_TICKET ame_ticket = db.AME_TICKET.Find(id);
            db.AME_TICKET.Remove(ame_ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

AmeWebApps/Views/Tickets/Create.cshtml
@model AmeWebApps.Models.AME_TICKET

@{
    ViewBag.Title = "Open New Ticket";
}

<header>
    <style>
        select {
            border:1px solid #e2e2e2;
            background: #fff;
            color: #333;
            font-size:1.2em;
            margin:5px 0 6px 0;
            padding: 5px;
            width: 312px;
        }
    </style>
    <script>
        $(document).ready(function () {
            $("#ASIGNEE")[0].selectedIndex = 0;
            $("#submit").click(function () {

                var ass = $('#ASIGNEE');
                if (ass.val() === '') {
                    alert("Please assign ticket!");
                    $('#ASIGNEE').focus();

                    return false;
                }
                else return;
            });
        });
    </script>
</header>

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>AME_TICKET</legend>

        <div class="editor-field">
            <input type="hidden" value="0" name="TICKET_ID" id="TICKET_ID"/>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.STATUS)
        </div>
        <div class="editor-field">
            <select name="STATUS" id="STATUS">
                <option value="OPEN">Open</option>
                <option value="PENDING">Pending</option>
                <option value="CLOSED">Closed</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENT_ID)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CLIENT_ID, new { @Value = ViewData["CLIENT_ID"] })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BRANCH)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.BRANCH, new { @Value = ViewData["BRANCH"] })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DATE_OPENED)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.DATE_OPENED, new { @Value = DateTime.Now })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ASIGNEE)
        </div>
        <div class="editor-field">
            <select id="ASIGNEE" name="ASIGNEE">
                <option value=""></option>
                <option value="AKrikorian">AKrikorian</option>
                <option value="PKrikorian">PKrikorian</option>
                <option value="SConnolly">SConnolly</option>
                <option value="JRogers">JRogers</option>
                <option value="MMakhool">MMakhool</option>
                <option value="JSmith">JSmith</option>
                <option value="KMiller">KMiller</option>
                <option value="AAvedissian">AAvedissian</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RECIEVER_TAG)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.RECIEVER_TAG, new { @Value = ViewData["COMPUTER_NAME"] })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.REASON_FOR_CALL)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REASON_FOR_CALL)
            @Html.ValidationMessageFor(model => model.REASON_FOR_CALL)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ESCALATED_TO)
        </div>
        <div class="editor-field">
            <select id="ESCALATED_TO" name="ESCALATED_TO">
                <option value=""></option>
                <option value="PKrikorian">PKrikorian</option>
                <option value="SConnolly">SConnolly</option>
                <option value="JRogers">JRogers</option>
                <option value="MMakhool">MMakhool</option>
                <option value="JSmith">JSmith</option>
                <option value="KMiller">KMiller</option>
                <option value="AAvedissian">AAvedissian</option>
            </select>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LAST_UPDATE)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.LAST_UPDATE, new { @Value = DateTime.Now })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PRIORITY)
        </div>
        <div class="editor-field">
            <select id="PRIORITY" name="PRIORITY">
                <option value="1">Normal</option>
                <option value="0">High</option>
                <option value="2">Low</option>
            </select>
        </div>

        <p>
            <input type="submit" id="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmeWebApps/Views/Tickets/Delete.cshtml
@model AmeWebApps.Models.AME_TICKET

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>AME_TICKET</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TICKET_ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TICKET_ID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.STATUS)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.STATUS)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CLIENT_ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CLIENT_ID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BRANCH)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BRANCH)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DATE_OPENED)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DATE_OPENED)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ASIGNEE)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ASIGNEE)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RECIEVER_TAG)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RECIEVER_TAG)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.REASON_FOR_CALL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.REASON_FOR_CALL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ESCALATED)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ESCALATED)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ESCALATED_TO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ESCALATED_TO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_UPDATE)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_UPDATE)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PRIORITY)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PRIORITY)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

AmeWebApps/Views/Tickets/Details.cshtml
@model AmeWebApps.Models.AME_TICKET

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>AME_TICKET</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TICKET_ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TICKET_ID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.STATUS)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.STATUS)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CLIENT_ID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CLIENT_ID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BRANCH)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BRANCH)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DATE_OPENED)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DATE_OPENED)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ASIGNEE)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ASIGNEE)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RECIEVER_TAG)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RECIEVER_TAG)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.REASON_FOR_CALL)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.REASON_FOR_CALL)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ESCALATED)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ESCALATED)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ESCALATED_TO)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ESCALATED_TO)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LAST_UPDATE)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LAST_UPDATE)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PRIORITY)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PRIORITY)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AmeWebApps/Views/Tickets/Edit.cshtml
@model AmeWebApps.Models.AME_TICKET

@{
    ViewBag.Title = "Update Ticket";
}

<header>
    <style>
        select {
            border: 1px solid #e2e2e2;
            background: #fff;
            color: #333;
            font-size: 1.2em;
            margin: 5px 0 6px 0;
            padding: 5px;
            width: 312px;
        }
    </style>
</header>

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>AME_TICKET</legend>
        <table>
            <tr>
                <td rowspan="2">

                    <div class="editor-field">
                        <input type="hidden" value="@Model.TICKET_ID" name="TICKET_ID" />
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.STATUS)
                    </div>
                    <div class="editor-field">
                        <select name="STATUS" id="STATUS" class="textarea">
                            <option value="OPEN">Open</option>
                            <option value="PENDING">Pending</option>
                            <option value="CLOSED">Closed</option>
                        </select>
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.CLIENT_ID)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.CLIENT_ID, new { @readonly = "readonly" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.BRANCH)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.BRANCH, new { @readonly = "readonly" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.DATE_OPENED)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.DATE_OPENED, new { @readonly = "readonly" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ASIGNEE)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ASIGNEE, new { @readonly = "readonly" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.RECIEVER_TAG)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.RECIEVER_TAG, new { @readonly = "readonly" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.REASON_FOR_CALL)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.REASON_FOR_CALL)
                        @Html.ValidationMessageFor(model => model.REASON_FOR_CALL)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ESCALATED_TO)
                    </div>
                    <div class="editor-field">
                        <select id="ESCALATED_TO" name="ESCALATED_TO">
                            <option value=""></option>
                            <option value="PKrikorian">PKrikorian</option>
                            <option value="SConnolly">SConnolly</option>
                            <option value="JRogers">JRogers</option>
                            <option value="MMakhool">MMakhool</option>
                            <option value="JSmith">JSmith</option>
                            <option value="KMiller">KMiller</option>
                            <option value="AAvedissian">AAvedissian</option>
                        </select>
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.LAST_UPDATE)
                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.LAST_UPDATE, new { @Value = DateTime.Now, @readonly = "readonly" })
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.PRIORITY)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.PRIORITY)
                        @Html.ValidationMessageFor(model => model.PRIORITY)
                    </div>
                </td>
                <td style="vertical-align:top;">
                    <div>
                        <h3 style="margin: 0px 0px 10px 0px;">Steps Taken</h3>
                        <input type="checkbox" id="cb_exp" name="cb_exp" value="true" @if(ViewBag.tSteps != null){if(ViewBag.tSteps.chk_expiration){<text>checked</text>}}/>Checked Expiration<br />
                        <input type="checkbox" name="cb_pwr" value="true" @if(ViewBag.tSteps != null){if(ViewBag.tSteps.chk_power){<text>checked</text>}}/>Checked Power<br />
                        <input type="checkbox" name="cb_cdtray" value="true" @if(ViewBag.tSteps != null){if(ViewBag.tSteps.chk_cd_tray){<text>checked</text>}}/>Checked CD Tray<br />
                        <input type="checkbox" name="cb_cables" value="true" @if(ViewBag.tSteps != null){if(ViewBag.tSteps.chk_cables){<text>checked</text>}}/>Checked Cables<br />
                        <input type="checkbox" name="cb_amp" value="true" @if(ViewBag.tSteps != null){if(ViewBag.tSteps.chk_amp){<text>checked</text>}}/>Checked Amplifier
                    </div>
                    <div>
                        <h3>Notes:</h3>
                        @foreach (var tNote in ViewBag.tNotes)
                        {
                            <p><b>@tNote.DATE_MODIFIED:@tNote.ADDED_BY</b><br />@tNote.TICKET_NOTE</p>
                        }
                    </div>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">
                    <div>
                        <h3>Add Notes</h3>
                        <textarea id="oNotes" name="oNotes"></textarea>
                    </div>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;">
                    <p>
                        <input type="submit" value="Save" />
                    </p>
                </td>
            </tr>
        </table>

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmeWebApps/Views/Tickets/FindReceiver.cshtml
@model AmeWebApps.Models.AME_SYSTEM_RETURNS

@{
    ViewBag.Title = "Search TAG Number";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}

@using (Html.BeginForm("Create","Tickets",FormMethod.Get)) {
    <label for="COMPUTER_NAME">TAG #:</label>
    <input type="text" id="COMPUTER_NAME" name="COMPUTER_NAME" />
    <input type="submit" value="Look Up" />
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>