AmeWebApps/Controllers/CommController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AmeWebApps.Controllers
{
    public class CommController : Controller
    {
        //
        // GET: /Comm/

        public ActionResult Index(string ds)
        {
            ViewBag.fileCount = 0;
            ViewBag.folderPath = "NULL";
            ViewBag.hashCount = 0;
            ViewBag.lastActivity = DateTime.Now.AddDays(-5);
            ViewBag.ds = ds;
            ViewBag.lastHashFile = null;
            ViewBag.hasntStarted = false;
           

            if (!String.IsNullOrEmpty(ds))
            {
                var file02Path = String.Format(@"\\AME-FILE-02\AMEUpdates\Disc Images\{0}", ds);
                var folderPath = String.Format(@"\\COMM-1\ame\Updates\Media\{0}", ds);

                if (Directory.Exists(folderPath))
                {

                    var imageFiles = Directory.GetFiles(folderPath, "*", SearchOption.AllDirectories);
                    var hashFiles = Directory.GetFiles(folderPath, "*.hash", SearchOption.AllDirectories);

                    int realCount = imageFiles.Except(hashFiles).Count() - 1;
                    int hashCount = hashFiles.Count();
                    if (hashCount == 0)
                    {
                        ViewBag.hasntStarted = true;
                    }
                    else
                    {

                        var lastHash = new DirectoryInfo(folderPath).GetFiles("*.hash", SearchOption.AllDirectories).OrderByDescending(f => f.CreationTime).FirstOrDefault();

                        ViewBag.lastActivity = lastHash.LastWriteTime;
                        ViewBag.lastHashFile = lastHash;
                        ViewBag.fileCount = realCount;
                        ViewBag.hashCount = hashCount;
                        ViewBag.folderPath = folderPath;
                        ViewBag.ds = ds;
                    }
                }
                else
                {
                    ViewBag.lastActivity = "N/A";
                    ViewBag.fileCount = "N/A";
                    ViewBag.hashCount = "N/A";
                    ViewBag.folderPath = "N/A";
                    ViewBag.ds = "N/A";
                }
            }
            
            return View();
        }

    }
}

AmeWebApps/Views/Comm/Index.cshtml
@{
    ViewBag.Title = "Is It Downloading?!";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@{
    using (Html.BeginForm("Index","Comm",FormMethod.Get)) {
        <label for="ds">Update Serial Number (i.e SC42069):</label>
        <input type="text" id="ds" name="ds" value="@ViewBag.ds"/>
        <input type="submit" value="Check Status" />
    } 
}

@{
    if(String.IsNullOrEmpty(ViewBag.ds)){
     <p>Please select update to search i.e. SC24953</p>   
    }
    if(!String.IsNullOrEmpty(ViewBag.ds) && ViewBag.hasntStarted == true && ViewBag.ds != "N/A"){
     <p><b>The update does not appear to have been copied to the comm server to begin downloading or no files have been downloaded.</b></p>   
    }
    if (!String.IsNullOrEmpty(ViewBag.ds) && ViewBag.ds != "N/A")
    {
    <p>
        @if (ViewBag.fileCount == ViewBag.hashCount)
        {
            <span><b>The download appears to be complete!</b></span>
        }
        else if (DateTime.Now.AddHours(-2.5) < ViewBag.lastActivity)
        {
            <span><b>Yes it is downloading!</b></span>
        }
        else
        {
            <span><b>No! It does not appear to be downloading.</b></span>   
        }
    </p>
    <p>Update Path: @ViewBag.folderPath</p>
    <p>Total FileCount: @ViewBag.fileCount</p>
    <p>Files Downloaded: @ViewBag.hashCount / @ViewBag.fileCount</p>
    <p>Last Activity: @ViewBag.lastActivity.ToString()</p>
        if (ViewBag.lastHashFile != null)
        {
            <p>File: @ViewBag.lastHashFile.FullName</p>
        }
    } else {
        <p><b>The update does not appear to have been copied to the comm server to begin downloading or no files have been downloaded.</b></p>   
    }
    
}