AmeWebApps/Controllers/ReturnedReceiversController.cs
using AmeWebApps.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace AmeWebApps.Controllers
{
    public class ReturnedReceiversController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PendingReturns()
        {
            List<PendingReturnModel> PendingReturnsList = new List<PendingReturnModel>();
            string connString = "server=WEB-APPS-1; database=AmeMaster; uid=sa; password=topdog;";

            using (SqlConnection conn = new SqlConnection(connString))
            {
                string sqlQry = "sp_getPendingReturns";
                using (SqlCommand cmd = new SqlCommand(sqlQry, conn))
                {
                    conn.Open();
                    SqlDataReader reader = cmd.ExecuteReader();
                    if (reader.HasRows)
                    {
                        while(reader.Read())
                        {
                            PendingReturnModel prm = new PendingReturnModel();
                        
                            if (!reader.IsDBNull(reader.GetOrdinal("BRANCH")))
                            prm.BRANCH = reader.GetString(reader.GetOrdinal("BRANCH"));
                            if (!reader.IsDBNull(reader.GetOrdinal("CLIENT_ID")))
                            prm.CLIENT_ID = reader.GetInt32(reader.GetOrdinal("CLIENT_ID"));
                            if (!reader.IsDBNull(reader.GetOrdinal("COMPANY_NAME")))
                            prm.COMPANY_NAME = reader.GetString(reader.GetOrdinal("COMPANY_NAME"));
                            if (!reader.IsDBNull(reader.GetOrdinal("PRINT_DATE")))
                            prm.PRINT_DATE = reader.GetString(reader.GetOrdinal("PRINT_DATE"));
                            if (!reader.IsDBNull(reader.GetOrdinal("PRINTED_BY")))
                            prm.PRINTED_BY = reader.GetString(reader.GetOrdinal("PRINTED_BY"));
                            if (!reader.IsDBNull(reader.GetOrdinal("REPLACING_NAME")))
                            prm.REPLACING_NAME = reader.GetString(reader.GetOrdinal("REPLACING_NAME"));
                            if (!reader.IsDBNull(reader.GetOrdinal("RETURN_SLIP_TRACKING_NUM")))
                            prm.RETURN_SLIP_TRACKING_NUM = reader.GetString(reader.GetOrdinal("RETURN_SLIP_TRACKING_NUM"));
                            PendingReturnsList.Add(prm);
                        }
                    }
                }
            }



            return View(PendingReturnsList);
        }

        public ActionResult AutoDiagnose(string tagNum)
        {
            if (tagNum.Contains("_"))
            {
                var filepath = "\\\\Amecomm\\ame\\Logs\\" + tagNum + "\\Faults.txt.gz";
                FileStream dest2 = System.IO.File.OpenRead(filepath);
                GZipStream myDecompressionStream = new GZipStream(dest2, CompressionMode.Decompress);
                FileStream ExtractedFile = System.IO.File.Create(@"C:\Faultss.txt");

                int mySecondByte = myDecompressionStream.ReadByte();

                while (mySecondByte != -1)
                {
                    ExtractedFile.WriteByte((byte)mySecondByte);
                    mySecondByte = myDecompressionStream.ReadByte();
                }

                ExtractedFile.Close();

                System.IO.StreamReader file = new System.IO.StreamReader(@"C:\Faultss.txt");

                List<string> faultList = new List<string>();
                string line;

                while ((line = file.ReadLine()) != null)
                {
                    if (line.Substring((line.Length - 2), 2) == "ON")
                    {
                        string date = line.Substring((line.Length - 17), 14);
                        DateTime dt = DateTime.ParseExact(date,"yyyyMMddHHmmss",null);
                        date = dt.ToString();

                        line = line.Substring(3, (line.Length - 20)) + " " + date;
                        faultList.Add(line);
                    }
                }
                

                ViewBag.faultList = faultList;
                ViewBag.tagNum = tagNum;
            }

            if (!String.IsNullOrEmpty(tagNum))
            {
                string connString = "server=192.168.0.24; database=AmeMaster; uid=sa; password=topdog;";
                try
                {
                    using (SqlConnection conn = new SqlConnection(connString))
                    {
                        string sqlQry = String.Format("select rcs.CLIENT_ID, rcs.DATE_LAST_COMM, rcs.SYSTEM_EXPIRES, rca.COMPANY_NAME, rca.BRANCH, rcs.COMPUTER_NAME, rcl.NOTES from RPM_CLIENT_SYSTEM rcs inner join RPM_CLIENT_LOCATION rcl on rcs.LOCATION_ID = rcl.LOCATION_ID inner join RPM_CLIENT_ADDRESS rca on rcl.ADDRESS_ID = rca.ADDRESS_ID where rcs.COMPUTER_NAME = '{0}'", tagNum);
                        using (SqlCommand cmd = new SqlCommand(sqlQry, conn))
                        {
                            conn.Open();
                            SqlDataReader reader = cmd.ExecuteReader();
                            if (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    ViewData["COMPUTER_NAME"] = reader.GetString(reader.GetOrdinal("COMPUTER_NAME"));
                                    ViewData["CLIENT_ID"] = reader.GetInt32(reader.GetOrdinal("CLIENT_ID")).ToString();
                                    ViewData["COMPANY_NAME"] = reader.GetString(reader.GetOrdinal("COMPANY_NAME"));
                                    ViewData["BRANCH"] = reader.GetString(reader.GetOrdinal("BRANCH"));
                                    ViewData["DATE_LAST_COMM"] = reader.GetDateTime(reader.GetOrdinal("DATE_LAST_COMM")).ToString();
                                    ViewData["SYSTEM_EXPIRES"] = reader.GetDateTime(reader.GetOrdinal("SYSTEM_EXPIRES")).ToString();
                                    var notes = reader.GetString(reader.GetOrdinal("NOTES"));
                                    notes = notes.Replace(System.Environment.NewLine, @"<br/>");
                                    ViewData["NOTES"] = notes.ToString();
                                }
                            }
                            conn.Close();
                        }
                    }
                }
                catch (Exception e32)
                {
                    Console.Write(e32.ToString());
                }
            }

            return View();
        }

        public ActionResult InputReturn()
        {

            return View();
        }

        public ActionResult InputReturn2(string COMPUTER_NAME)
        {
            
            if (!String.IsNullOrEmpty(COMPUTER_NAME))
            {
                string connString = "server=192.168.0.24; database=AmeMaster; uid=sa; password=topdog;";
                try
                {
                    using (SqlConnection conn = new SqlConnection(connString))
                    {
                        if (COMPUTER_NAME.Length > 6)
                        {
                            COMPUTER_NAME = COMPUTER_NAME.Substring(4, 6);
                        }
                        string sqlQry = String.Format("select rcs.CLIENT_ID, rca.COMPANY_NAME, rca.BRANCH, rcs.COMPUTER_NAME, rcl.NOTES from RPM_CLIENT_SYSTEM rcs inner join RPM_CLIENT_LOCATION rcl on rcs.LOCATION_ID = rcl.LOCATION_ID inner join RPM_CLIENT_ADDRESS rca on rcl.ADDRESS_ID = rca.ADDRESS_ID where rcs.COMPUTER_NAME like 'AME_{0}'", COMPUTER_NAME);
                        using (SqlCommand cmd = new SqlCommand(sqlQry, conn))
                        {
                            conn.Open();
                            SqlDataReader reader = cmd.ExecuteReader();
                            if (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    ViewData["COMPUTER_NAME"] = reader.GetString(reader.GetOrdinal("COMPUTER_NAME"));
                                    ViewData["CLIENT_ID"] = reader.GetInt32(reader.GetOrdinal("CLIENT_ID")).ToString();
                                    ViewData["COMPANY_NAME"] = reader.GetString(reader.GetOrdinal("COMPANY_NAME"));
                                    ViewData["BRANCH"] = reader.GetString(reader.GetOrdinal("BRANCH"));
                                    var notes = reader.GetString(reader.GetOrdinal("NOTES"));
                                    notes = notes.Replace(System.Environment.NewLine, @"<br/>");
                                    ViewData["NOTES"] = notes.ToString();
                                }
                            }
                            conn.Close();
                        } 
                    }
                }
                catch (Exception e32)
                {
                    Console.Write(e32.ToString());
                }
            }

            return View();
        }

        public ActionResult InputReturn3(string RETURN_DATE, int CLIENT_ID, string BRANCH, string COMPUTER_NAME, string RETURN_REASON, string REPLACED_BY)
        {
            string connString = "server=WEB-APPS-1; database=AmeMaster; uid=sa; password=topdog;";
            try
            {
                using (SqlConnection conn = new SqlConnection(connString))
                {
                    string insertStr = String.Format("INSERT INTO AME_SYSTEM_RETURNS (RETURN_DATE, CLIENT_ID, BRANCH, COMPUTER_NAME, RETURN_REASON, REPLACED_BY) values ('{0}', {1}, '{2}', '{3}', '{4}', '{5}')", RETURN_DATE, CLIENT_ID, BRANCH, COMPUTER_NAME, RETURN_REASON, REPLACED_BY);

AmeWebApps/Views/ReturnedReceivers/AddReturnIssue.cshtml
@model AmeWebApps.Models.AME_SYSTEM_RETURNS

@{
    ViewBag.Title = "Add Return Issue";
}

<h2>AddReturnIssue</h2>

@using (Html.BeginForm("UpdateReturnIssue", "ReturnedReceivers"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>AME_SYSTEM_RETURNS</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RETURN_ID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RETURN_ID)
            @Html.ValidationMessageFor(model => model.RETURN_ID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.COMPUTER_NAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.COMPUTER_NAME)
            @Html.ValidationMessageFor(model => model.COMPUTER_NAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RETURN_REASON)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RETURN_REASON)
            @Html.ValidationMessageFor(model => model.RETURN_REASON)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.REPLACED_BY)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.REPLACED_BY)
            @Html.ValidationMessageFor(model => model.REPLACED_BY)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ISSUES)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ISSUES)
            @Html.ValidationMessageFor(model => model.ISSUES)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmeWebApps/Views/ReturnedReceivers/AutoDiagnose.cshtml
@{
    ViewBag.Title = "Auto Diagnose Test";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}
<h2>Computer</h2>
<p>
    Tag: @ViewBag.tagNum
</p>

<h1>Issues</h1>
<p>
    Faults: @{foreach (var fault in ViewBag.faultList)
              {
                  <br />@fault
              }}
</p>
<p>
    Last Communication: <br /> @ViewData["DATE_LAST_COMM"]
</p>
<p>
    System Expires: <br /> @ViewData["SYSTEM_EXPIRES"]
</p>

AmeWebApps/Views/ReturnedReceivers/Index.cshtml
@{
    ViewBag.Title = "Returned Receiver Index";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}

<ul>
    <li>@Html.ActionLink("Input Returned Receiver", "InputReturn", "ReturnedReceivers")</li>
    <li>@Html.ActionLink("View Returned Receivers", "ViewReturns", "ReturnedReceivers")</li>
</ul>

AmeWebApps/Views/ReturnedReceivers/InputReturn.cshtml
@{
    ViewBag.Title = "Input Return";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}

@using (Html.BeginForm("InputReturn2","ReturnedReceivers",FormMethod.Get)) {
    <label for="COMPUTER_NAME">TAG #:</label>
    <input type="text" id="COMPUTER_NAME" name="COMPUTER_NAME" />
    <input type="submit" value="Look Up" />
}

<div>
    @Html.ActionLink("Back to List", "ViewReturns")
</div>

AmeWebApps/Views/ReturnedReceivers/InputReturn2.cshtml
@model AmeWebApps.Models.AME_RETURNED_RECEIVERS

@{
    ViewBag.Title = "Input Return";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}
<div style="position:relative;">
<div>
@using (Html.BeginForm("InputReturn3", "ReturnedReceivers")) {
    <fieldset>
        <legend>AME_RETURNED_RECEIVERS</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.RETURN_DATE)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.RETURN_DATE, new { @Value = DateTime.Now.ToString() })
            @Html.ValidationMessageFor(model => model.RETURN_DATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENT_ID)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CLIENT_ID, new { @Value = ViewData["CLIENT_ID"] })
            @Html.ValidationMessageFor(model => model.CLIENT_ID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENT_NAME)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CLIENT_NAME, new { @Value = ViewData["COMPANY_NAME"] })
            @Html.ValidationMessageFor(model => model.CLIENT_NAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BRANCH)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.BRANCH, new { @Value = ViewData["BRANCH"] })
            @Html.ValidationMessageFor(model => model.BRANCH)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.COMPUTER_NAME)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.COMPUTER_NAME, new { @Value = ViewData["COMPUTER_NAME"] })
            @Html.ValidationMessageFor(model => model.COMPUTER_NAME)
        </div>

        <div class="editor-label">
            <label for="RETURN_REASON">Return Reason</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RETURN_REASON)
            @Html.ValidationMessageFor(model => model.RETURN_REASON)
        </div>

        <div class="editor-label">
            <label for="RETURNED_BY">Replaced By</label>
        </div>
        <div class="editor-field">
            <select id="REPLACED_BY" name="REPLACED_BY">
                <option value="PKrikorian">PKrikorian</option>
                <option value="SConnolly">SConnolly</option>
                <option value="JRogers">JRogers</option>
                <option value="MMakhool">MMakhool</option>
                <option value="JSmith">JSmith</option>
                <option value="KMiller">KMiller</option>
                <option value="AAvedissian">AAvedissian</option>
            </select>
        </div>
        <p>
            <input type="submit" value="Input" />
        </p>
    </fieldset>
}
</div>
<div style="width:400px; top:0px;left:440px;position:absolute;">
    <table style="font:10px arial;">
        <tr>
            <td>@ViewData["CLIENT_ID"]</td>
            <td>@ViewData["COMPANY_NAME"]</td>
            <td>@ViewData["BRANCH"]</td>
        </tr>
    </table>
    <br />
    <br />
        @{if (ViewData["NOTES"] == null)
          {
          <p>"No return notes"</p>
          }
          else
          { 
            <p>@Html.Raw(ViewData["NOTES"])</p>
          }
          }
</div>
</div>
<div>
    @Html.ActionLink("Back to Search", "InputReturn")
    <br />
    @Html.ActionLink("Back to List", "ViewReturns")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmeWebApps/Views/ReturnedReceivers/InputReturn3.cshtml
@{
    ViewBag.Title = "Input Successful";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
        </div>
    </section>
}

<p>
    The return has been successfully added.
</p>

<div>
    @Html.ActionLink("Back to Search", "InputReturn")
    <br />
    @Html.ActionLink("Back to List", "ViewReturns")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmeWebApps/Views/ReturnedReceivers/PendingReturns.cshtml
@model List<AmeWebApps.Models.PendingReturnModel>

@{
    ViewBag.Title = "Pending Returns";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 50);
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@section scripts{
<script>
    function getTracking(trackingNum) {
        var url = "http://wwwapps.ups.com/WebTracking/track?track=yes&trackNums=" + trackingNum;
        window.open(url);
    }
</script>

}

@grid.GetHtml(
tableStyle: "webGrid",
headerStyle: "header",
alternatingRowStyle: "alt",
columns: grid.Columns(
    grid.Column(columnName: "PRINT_DATE", header: "Date Replaced"),
    grid.Column(columnName: "COMPANY_NAME", header: "Company"),
    grid.Column(columnName: "BRANCH", header: "Branch"),
    grid.Column(columnName: "REPLACING_NAME", header: "Returning"),
    grid.Column(columnName: "RETURN_SLIP_TRACKING_NUM", header: "Return Slip", format: @<text>@if(item.RETURN_SLIP_TRACKING_NUM != ""){<button onclick="getTracking('@(item.RETURN_SLIP_TRACKING_NUM)')">@item.RETURN_SLIP_TRACKING_NUM</button>}</text>),
    grid.Column(columnName: "PRINTED_BY", header: "Printed By")
))

AmeWebApps/Views/ReturnedReceivers/ViewReturns.cshtml
@model List<AmeWebApps.Models.AME_SYSTEM_RETURNS>

@{
    ViewBag.Title = "View Returned Recievers";
    WebGrid grid = new WebGrid(Model, rowsPerPage: 50);
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title</h1>
            </hgroup>
        </div>
    </section>
}

@grid.GetHtml(
tableStyle: "webGrid",
headerStyle: "header",
alternatingRowStyle: "alt",
columns: grid.Columns(
grid.Column(columnName: "RETURN_DATE", header:"Return Date"),
    grid.Column(columnName: "CLIENT_ID", header: "Client ID"),
    grid.Column(columnName:"BRANCH", header: "Branch"),
    grid.Column(columnName:"COMPUTER_NAME", header: "Tag Number"),
    grid.Column(columnName:"RETURN_REASON", header: "Reason for Return", format: item => String.IsNullOrEmpty(item.RETURN_REASON) ? "None" : item.RETURN_REASON),
    grid.Column(columnName:"REPLACED_BY", header: "Replaced By"),
    grid.Column(columnName:"ISSUES", header: "Receiver Issues", format: item => String.IsNullOrEmpty(item.ISSUES) ? Html.ActionLink((string)"Add Issue", (string)"AddReturnIssue", new { returnID = (int)item.RETURN_ID}) : item.ISSUES)
    ))

<br />
<div>
    @Html.ActionLink("Back to Search", "InputReturn")
</div>